import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.FileOutputStream;
import java.util.Date;

class CreaPDF {
    //TODO: MODIFICARE CON LA VOSTRA PATH
    private static String FILE = "./FirstPdf.pdf";
    
    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
            Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);
    
    public CreaPDF() {
    }
    
    public static void main(String[] args) {
        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(FILE));
            document.open();
            addTitlePage(document);
            addContent(document);
            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private static void addTitlePage(Document document) throws DocumentException {
        Paragraph preface = new Paragraph();
        
        // We add one empty line
        preface.add(new Paragraph(" "));
        
        // Lets write a big header
        preface.add(new Paragraph("TITOLO", catFont));
        
        preface.add(new Paragraph(" "));
        
        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph("PDF Creato il: " + new Date(),smallBold));
        
        document.add(preface);
    }
    
    private static void addContent(Document document) throws DocumentException {
        Anchor anchor = new Anchor("First Chapter", catFont);
        anchor.setName("First Chapter");
        
        // Second parameter is the number of the chapter
        Chapter catPart = new Chapter(new Paragraph(anchor), 1);
        
        Paragraph subPara = new Paragraph("Subcategory 1", subFont);
        Section subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("Hello"));
        
        subPara = new Paragraph("Subcategory 2", subFont);
        subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("Paragraph 1"));
        subCatPart.add(new Paragraph("Paragraph 2"));
        subCatPart.add(new Paragraph("Paragraph 3"));
        
        // now add all this to the document
        document.add(catPart);
    }
    
}

